export const ACTIVITY = "ACTIVITY";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const DETAIL_ACTIVITY = "DETAIL_ACTIVITY";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const ADD_CARDTODO = "ADD_CARDTODO";
export const UPDATE_CARDTODO = "UPDATE_CARDTODO";
export const DELETE_CARDTODO = "DELETE_CARDTODO";

export const MODAL_MESSAGE = "MODAL_MESSAGE";
